server:
  port: 8080
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8
  servlet:
    context-path: /mn-web

spring:
  application:
    name: mn-web
  datasource:
    name: mn-web
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://127.0.0.1:3306/mn?serverTimezone=Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver

#测试属性赋值
person:
  lastName: zhangsan
  age: 20
  boss: false
  birth: 2018/12/12
  mapObj: {key1: v1,key2: 12}
  lists:
    - lisi
    - zhaoliu
  dog:
    name: 旺财
    age: 2

